set(CMAKE_SYSTEM_NAME generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TOOLCHAIN_PATH /usr/bin)
set(TOOLCHAIN_NAME arm-none-eabi-)

set(CMAKE_C_COMPILER ${TOOLCHAIN_PATH}/${TOOLCHAIN_NAME}g++)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PATH}/${TOOLCHAIN_NAME}g++)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PATH}/${TOOLCHAIN_NAME}g++)
set(CMKAE_OBJCOPY ${TOOLCHAIN_PATH}/${TOOLCHAIN_NAME}objcopy)
set(CMKAE_SIZE ${TOOLCHAIN_PATH}/${TOOLCHAIN_NAME}size)
